# Generated by Django 3.0.5 on 2020-04-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_price_model_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='model_no',
        ),
    ]
