# Generated by Django 3.0.5 on 2020-04-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_price_model_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='model_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_id +', to='djangoapp.Item'),
        ),
    ]
