# Generated by Django 3.0.5 on 2020-04-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20200413_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='model_no',
        ),
    ]
