# Generated by Django 3.0.5 on 2020-04-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_remove_price_model_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='item_id',
            new_name='item',
        ),
    ]
