# Generated by Django 3.0.5 on 2020-04-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_auto_20200418_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='item_id',
            field=models.CharField(max_length=100),
        ),
    ]
