# Generated by Django 3.0.5 on 2020-04-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_auto_20200418_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Item'),
        ),
    ]
